### ISSUE TITLE
拿不到最新版本的记录

### ISSUE THREAD

**Issue by shikui08** [hedzr/undo-cxx#1]
如题。想获取经过一系列undo/redo操作后的最新版本的值,看代码undo-zcore.hh里面应该是_position-1处的值。目前拿不到。得修改.

**Comment by shikui08** [comment]
这个需求应该是比较常见的吧,有没有考虑加下。

**Comment by hedzr** [comment]
do u mean `focused_item()`?

**Comment by hedzr** [comment]
if you were trying to modified test/undo.cc line 143 to:

```c++
undoable_cmd_system.invoke<UndoCmdT>("undo 1");
std::cout << "  > focused item: " << *undoable_cmd_system.focused_item() << '\n';
undoable_cmd_system.invoke<UndoCmdT>("undo 2");
std::cout << "  > focused item: " << *undoable_cmd_system.focused_item() << '\n';
...
```

Is that what u want?

**Comment by shikui08** [comment]
> if you were trying to modify test/undo.cc line 143 to:
> 
> ```c++
> undoable_cmd_system.invoke<UndoCmdT>("undo 1");
> std::cout << "  > focused item: " << *undoable_cmd_system.focused_item() << '\n';
> undoable_cmd_system.invoke<UndoCmdT>("undo 2");
> std::cout << "  > focused item: " << *undoable_cmd_system.focused_item() << '\n';
> ...
> ```
> 
> Is that what u want?

我理解focused_item()指向的是next available的元素。例子里面如果不进行undo操作,那么_position就一直等于end(), 访问它的话程序直接崩了。我这是linux。windows下面没测。

**Comment by shikui08** [comment]
.....................
undoable_cmd_system.invoke<CommandT>("first ever command");
std::cout << "  > focused item: " << *undoable_cmd_system.focused_item() << '\n';  //这里就crash了。

**Comment by hedzr** [comment]
so you need the accessors like front()/back() on the member _saved_states, do you? that's not focused, it is back(). if true, i can add these apis to class `undoable_cmd_system_t` at the next commit:

```c++
    MementoPtr &newest_item() { return _saved_states.back(); }
    MementoPtr const &newest_item() const { return _saved_states.back(); }
    MementoPtr &oldest_item() { return _saved_states.front; }
    MementoPtr const &oldest_item() const { return _saved_states.front(); }
```

waiting for your advices

**Comment by hedzr** [comment]
it may be misunderstood about your request. i re-read(ed), and i think these is your fav:

```c++
MementoPtr &newest_item() { auto it=_position; it--; return *it; }
```

do i get it finally?

**Comment by shikui08** [comment]
> it may be misunderstood about your request. i re-read(ed), and i think this is your fav:
> 
> ```c++
> MementoPtr &newest_item() { auto it=_position; it--; return *it; }
> ```
> 
> do i get it finally?

的确是这个意思。Thanks for your time!

**Comment by hedzr** [comment]
fine. the commits and release will be pushed before 7am+0800 tomorrow. just keep tracing on this issue.
thanks your advice.

**Comment by hedzr** [comment]
checked and close now.
